# Generated by Django 4.2 on 2024-07-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Tank Top', 'Tank Top'), ('Swimwear', 'Swimwear'), ('Sundress', 'Sundress'), ('Bright', 'Bright')], default='Men', max_length=20),
        ),
    ]
